package com.project.JewelryMS.model;

import lombok.Data;

@Data
public class CreateCustomerRequest {//for Create methods, with the id autogenerated
    String email;
    String phoneNumber;
    int pointAmount;
}