package com.project.JewelryMS.model.Customer;

import lombok.Data;

@Data
public class CreateCustomerRequest {//for Create methods, with the id autogenerated
    String cusName;
    String email;
    String phoneNumber;
    String gender;
    Integer staff_ID;
}