package com.project.JewelryMS.model.Customer;

import lombok.Data;

@Data
public class CreateCustomerRequest {//for Create methods, with the id autogenerated
    String email;
    String phoneNumber;
    String gender;
}